networks:
  phplab_network:
    name: phplab_network

services:
  nginx:
    container_name: phplab_nginx
    image: nginx
    ports: 
      - 80:80
    volumes:
      - .\vhost.conf:/etc/nginx/conf.d/default.conf
      - .\www:/var/www/
    networks:
      - phplab_network
    depends_on:
      - php
      - mysql
  php:
    container_name: phplab_php
    build: ./images/php
    volumes:
      - .\www/public:/var/www/public
    networks:
      - phplab_network
    depends_on:
      - mysql
  mysql:
    container_name: phplab_mysql
    image: mysql
    volumes:
      - .\mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=InsanePassword
    networks: 
      - phplab_network
  phpmyadmin:
    container_name: phplab_phpmyadmin
    image: phpmyadmin
    ports:
      - 1500:80
    environment:
      - PMA_HOST=phplab_mysql
    networks:
      - phplab_network
    depends_on:
      - mysql